LoLBank/routes.py
from flask import Blueprint, render_template, request

from .extensions import db
from .forms import (ClientForm, AdvisorForm, AccountForm, UpdateClient,
                    DeleteForm, TablesForm)
# NOTE: Won't work until we finish models.py
from .models import clients, addresses
# from .models import addresses, clients, accounts
# from .models import financial_advisors, clients_accounts, clients_advisors


main = Blueprint('main', __name__)


@main.route('/')
def index():
    return render_template('index.html')


@main.route('/add_client', methods=['GET', 'POST'])
def add_client():

    form = ClientForm()

    if form.validate_on_submit():
        ssn = form.ssn.data
        first_name = form.first_name.data
        last_name = form.last_name.data
        city = form.city.data
        state = form.state.data
        house_number = form.house_number.data
        zip_code = form.zip_code.data
        email = form.email.data

        new_address= addresses(
                               city=city,
                               state=state,
                               house_number=house_number,
                               #address_id=address_id,
                               zip_code=zip_code                               
        )

        new_client = clients(
                            ssn=ssn,
                            first_name=first_name,
                            last_name=last_name,
                            email=email,
                            address_id=new_address
        )

        db.session.add(new_client)
        db.session.add(new_address)
        db.session.commit()

        print("Client added to the database")

    return render_template('add_client.html', form=form)


@main.route('/add_advisor', methods=['GET', 'POST'])
def add_advisor():

    form = AdvisorForm()

    if form.validate_on_submit():
        first_name = form.first_name.data
        last_name = form.last_name.data
        area_of_expertise = form.expertise.data

    return render_template('add_advisor.html', form=form)

# at least one SELECT utilize a search/filter with a dynamically populated
# list of properties
@main.route('/search_database', methods=['GET', 'POST'])
def search_database():
    return render_template('search_database.html')

# add an account to an existing user
@main.route('/add_account', methods=['GET', 'POST'])
def add_account():
    form = AccountForm()
    if form.validate_on_submit():
        id = form.id.data
    # else:
        # return error message if invalid id entered

    return render_template('add_account.html', form=form)


@main.route('/update_client',  methods=['GET', 'POST'])
def update_client():
    form = UpdateClient()
    if form.validate_on_submit():
        id = form.id.data
        # return (return client data)
    # else:
        # return error message if invalid id entered

    return render_template('update_client.html', form=form)


@main.route('/delete_client', methods=['GET', 'POST'])
def delete_client():
    form = DeleteForm()

    if form.validate_on_submit():
        id = form.id.data

    return render_template('delete_client.html', form=form)


@main.route('/view_tables', methods=['GET', 'POST'])
def view_tables():
    form = TablesForm()
    if form.validate_on_submit():

        table_wanted = form.tables.data
        print(table_wanted)

    if form.validate_on_submit():
        if table_wanted == "clients":
            print("User wants clients")            
            client_table = clients.query.all()
            for x in client_table:
                print(x.first_name)

            return render_template('client_table.html', form=form, client_table=client_table)
    
    if form.validate_on_submit():
        if table_wanted == "addresses":
            print("User wants addresses")            
            address_table = addresses.query.all()
            for x in address_table:
                print(x.state)
            
            return render_template('address_table.html', form=form, address_table=address_table)

        # clients = clients.form.data
        # addresses = form.addresses.data
        # accounts = form.accounts.data
        # financial_advisors = form.financial_advisors.data
        # clients_advisors = form.clients_advisors.data
        # clients_accounts = form.clients_accounts.data
    return render_template('view_tables.html', form=form)

LoLBank/templates/add_account.html
{% extends "base.html" %}
{% block content %}
<div class="jumbotron">
  <h1>Add an account for a Client</h1>
  <form method="POST">
    {{ form.hidden_tag() }}
    {{ form.id.label }} {{form.id}} <br>
    {{ form.submit() }} 
  </form>
</div>
{% endblock %}

LoLBank/templates/add_advisor.html
{% extends "base.html" %}
{% block content %}
<div class="jumbotron">
  <h1>Add Financial Advisor</h1>
  <form method="POST">
    {{ form.hidden_tag() }}
    {{ form.first_name.label }} {{form.first_name}} <br>
    {{ form.last_name.label }} {{form.last_name}} <br>
    {{ form.expertise.label }} {{form.expertise}} <br>
    {{ form.submit() }} 
  </form>
</div>
{% endblock %}

LoLBank/templates/add_client.html
{% extends "base.html" %}
{% block content %}
<div class="jumbotron">
  <h1>Client Information</h1>
  <form method="POST" action="{{ url_for('main.add_client') }}">
    {{ form.hidden_tag() }}
    {{ form.ssn.label }} {{form.ssn}} <br>
    {{ form.first_name.label }} {{form.first_name}} <br>
    {{ form.last_name.label }} {{form.last_name}} <br>
    {{ form.city.label }} {{form.city}} <br>
    {{ form.state.label }} {{form.state}} <br>
    {{ form.house_number.label }} {{form.house_number}} <br>
    {{ form.zip_code.label }} {{form.zip_code}} <br>
    {{ form.email.label }} {{form.email}} <br>
    {{ form.submit() }} 
  </form>
</div>
{% endblock %}

LoLBank/templates/address_table.html
{% extends "view_tables.html" %}
{% block content %}

<h1>Address Table:</h1>
<table class="table">
    <tr>
        <th>Address ID</th>
        <th>City</th>
        <th>State</th>
        <th>House Number</th>
        <th>Zip Code</th>
        <th>Client Id</th>
    </tr>

    {% for address_item in address_table %}
    <tr>
        <td>{{address_item.address_id}}</td>
        <td>{{address_item.city}}</th>
        <td>{{address_item.state}}</th>
        <td>{{address_item.house_number}}</td>
        <td>{{address_item.zip_code}}</th>
        <td>{{address_item.client_id}}</td>        
    </tr>
    {% endfor %}
</table>


{% endblock %}

LoLBank/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <title>Land Of Lakes Bank</title>
  </head>
  <body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="navbar-nav">
        <a class="nav-item nav-link" href=" {{ url_for('main.index') }}">Home</a>
        <a class="nav-item nav-link" href=" {{ url_for('main.add_client') }}">Add Client</a>
        <a class="nav-item nav-link" href="{{ url_for('main.add_advisor') }} ">Add Financial Advisor</a>
        <a class="nav-item nav-link" href="{{ url_for('main.search_database') }} ">Search Database</a>
        <a class="nav-item nav-link" href="{{ url_for('main.add_account') }}">Add Account</a>
        <a class="nav-item nav-link" href="{{ url_for('main.update_client') }}">Update Client</a>
        <a class="nav-item nav-link" href="{{ url_for('main.delete_client') }}">Delete Client</a>
        <a class="nav-item nav-link" href="{{ url_for('main.view_tables') }}">View Tables</a>
      </div>
    </nav>

    {% block content %}

    {% endblock %}
  </body>
</html>

LoLBank/templates/client_table.html
{% extends "view_tables.html" %}
{% block content %}
<h1>Client Table:</h1>
<table class="table">
    <tr>
        <th>ID</th>
        <th>SSN</th>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Email</th>
        <th>City</th>
        <th>State</th>
        <th>Zip</th>
    </tr>
    {% for client in client_table %}
    <tr>
        <td>{{client.client_id}}</td>
        <td>{{client.ssn}}</th>
        <td>{{client.first_name}}</th>
        <td>{{client.last_name}}</td>
        <td>{{client.email}}</th>
        <td>{{client.address_id.city}}</td>
        <td>{{client.address_id.state}}</td>
        <td>{{client.address_id.zip_code}}</td>
    </tr>
    {% endfor %}
</table>

{% endblock %}

LoLBank/templates/delete_client.html
{% extends "base.html" %}
{% block content %}
<div class="jumbotron">
  <h1>Delete Client</h1>
  <form method="POST">
    {{ form.hidden_tag() }}
    {{ form.id.label }} {{form.id}} <br>
    {{ form.submit() }} 
  </form>
</div>
{% endblock %}

LoLBank/templates/index.html
{% extends "base.html" %}
{% block content %}
<div class="jumbotron">
  <h1>Welcome to The Land of Lakes Bank</h1>
  <p>Please select the appropriate CRUD Functionality from the Navbar</p>
</div>
{% endblock %}

LoLBank/templates/search_database.html
{% extends "base.html" %}
{% block content %}
<div class="jumbotron">
  <h1>Search The Database</h1>
</div>

<h2>We will search a client by id and populate requested data</h2> 
{% endblock %}

LoLBank/templates/update_client.html
{% extends "base.html" %}
{% block content %}
<div class="jumbotron">
  <h1>Update Client</h1>
  <form method="POST">
    {{ form.hidden_tag() }}
    {{ form.id.label }} {{form.id}} <br>
    {{ form.ssn.label }} {{form.ssn}} <br>
    {{ form.first_name.label }} {{form.first_name}} <br>
    {{ form.last_name.label }} {{form.last_name}} <br>
    {{ form.city.label }} {{form.city}} <br>
    {{ form.house_number.label }} {{form.house_number}} <br>
    {{ form.zip_code.label }} {{form.zip_code}} <br>
    {{ form.email.label }} {{form.email}} <br>
    {{ form.submit() }} 
  </form>
</div>
{% endblock %}

LoLBank/templates/view_tables.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <title>Land Of Lakes Bank</title>
  </head>
  <body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="navbar-nav">
        <a class="nav-item nav-link" href=" {{ url_for('main.index') }}">Home</a>
        <a class="nav-item nav-link" href=" {{ url_for('main.add_client') }}">Add Client</a>
        <a class="nav-item nav-link" href="{{ url_for('main.add_advisor') }} ">Add Financial Advisor</a>
        <a class="nav-item nav-link" href="{{ url_for('main.search_database') }} ">Search Database</a>
        <a class="nav-item nav-link" href="{{ url_for('main.add_account') }}">Add Account</a>
        <a class="nav-item nav-link" href="{{ url_for('main.update_client') }}">Update Client</a>
        <a class="nav-item nav-link" href="{{ url_for('main.delete_client') }}">Delete Client</a>
        <a class="nav-item nav-link" href="{{ url_for('main.view_tables') }}">View Tables</a>
      </div>
    </nav>
    <div class="jumbotron">
      <h1>View Tables</h1>
      <form method="POST">
        {{ form.hidden_tag() }}
        {{ form.tables.label }} {{form.tables}} <br>
        {{ form.submit() }} 
      </form>
    </div>
    {% block content %}
    
    {% endblock %}
  </body>
</html>